service: eventbridge-proxy

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  localPath: './../../../../../../'
  modules:
    - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - eventbridge:
        path: /eventbridge
        method: post
        eventBusName: { Ref: 'YourBus' }
        cors: true

resources:
  Resources:
    YourBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: YourEventBus-${self:provider.stage}-single